version: "3.8"

services:
  app:
    image: wikipedia-clone-app:dev
    build:
      context: ./app/
      target: DEV
    ports:
      - 8080:8080
    volumes: 
      - ./app/:/home/node
  server:
    image: wikipedia-clone-server:dev
    build:
      context: .
      target: DEV
    ports:
      - 8000:8000
    volumes: 
      - ./:/home/node

